spring:
    cloud:
        stream:
            bindings:
                domainProcessor-in-0:
                    destination: web-domains
                domainProcessor-out-0:
                    destination: active.web-domains
            function:
                definition: domainProcessor
            kafka:
                bindings:
                    domainProcessor-in-0:
                        consumer:
                            configuration:
                                value:
                                    deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                    domainProcessor-out-0:
                        producer:
                            configuration:
                                value:
                                    serializer: org.springframework.kafka.support.serializer.JsonSerializer
