spring:
    cloud:
        stream:
            bindings:
                domainService-in-0:
                    destination: active.web-domains
            function:
                definition: domainService
            kafka:
                bindings:
                    domainService-in-0:
                        consumer:
                            configuration:
                                value:
                                    deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
